#stravis config file
#made and maintained by Team Martini

#services
services:
  - mongodb$
#sudo option
sudo: required
#matrix
matrix:
  include:
    - python: "2.7"
    - pip install pymongo
#scripts to execute efore mongodb starts
before_script:
  - sleep 15
  #- mongo translator_db --eval 'db.addUser({user:"user1",pwd:"Azerty123",roles:[]});'
  - cd 'Java Backend/'
#language settings
language: java
#jdktag
jdk:
  - oraclejdk8
#deploy app on heroku
deploy:
  provider: heroku
  api_key: 049c3870-b65b-417b-8b86-c99261030ca3
  app: teammartini

#not working?
#install modules
#install:
  #- pip install pymongo
  #- python setup.py install
#install modules
#install:
  #- git clone git://github.com/mongodb/mongo-python-driver.git pymongo
  #- cd pymongo/
  #- python setup.py install

#before_script:
  #- python importDataScript.py
