#stravis config file
#made and maintained by Team Martini

#language settings
language: java
#jdktag
jdk:
  - oraclejdk8
#services
services:
  - mongodb
#scripts to execute efore mongodb starts
before_script:
  - sleep 15
  - mongo projectDB --eval 'db.addUser({user:"user1",pwd:"Azerty123",roles:[]});'
  - cd 'java Backend'
  - ant compile
  - ant jar
  - ant run  