#stravis config file
#made and maintained by Team Martini

#services
services:
  - mongodb
#sudo option
sudo: required
#scripts to execute efore mongodb starts
before_script:
  - python importDataScript.py
  - sleep 15
  - mongo TeamMartini --eval 'db.addUser({user:"user1",pwd:"Azerty123",roles:[]});'
  - cd 'Java Backend/'
install:
  - sudo apt-get install python-pip python-dev build-essential
  - sudo pip install pymongo
#language settings
language: java
#jdktag
jdk:
  - oraclejdk8
script:
  - gradle build
#deploy app on heroku
deploy:
  provider: heroku
  api_key: 049c3870-b65b-417b-8b86-c99261030ca3
  app: teammartini
