#shippable config file
#made and maintained by Team Martini

#language settings
language: java
#jdktag
jdk:
	- oraclejdk8

services:
  - mongodb

before_script:
  - mongo projectDB --eval 'db.createUser({user:"user1",pwd:"Azerty123",roles:[]});'